apiVersion: billingbudgets.cnrm.cloud.google.com/v1beta1
kind: BillingBudgetsBudget
metadata:
  name: ph-01hmjy78ee6bs4jebcd8rep7zk-budget # kpt-set: ${project-dept}-${project-unique-id}-budget
  namespace: "config-control"
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
  labels:
    vanity-name: "phx-test2" # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
    classification: dummy # kpt-set: ${project-classification}
spec:
  billingAccountRef:
    external: "016B6D-6AB281-505940" # kpt-set: ${billing-id}
  displayName: ph-test2-budget # kpt-set: ${project-dept}-${project-vanity-name}-budget
  budgetFilter:
    projects:
      - name: "phx-01hmjy78ee6bs4jebcd8rep7zk" # kpt-set: ${project-dept}${project-env}-${project-unique-id}
    calendarPeriod: "YEAR"
  amount:
    specifiedAmount:
      currencyCode: "CAD"
      units: 2000
  thresholdRules:
    - thresholdPercent: 0.5
      spendBasis: "CURRENT_SPEND"
    - thresholdPercent: 0.9
      spendBasis: "CURRENT_SPEND"
    - thresholdPercent: 1.0
      spendBasis: "CURRENT_SPEND"
