apiVersion: billingbudgets.cnrm.cloud.google.com/v1beta1
kind: BillingBudgetsBudget
metadata:
  name: dept-01hq9k6djknb0v0emv93wqkw42-budget # kpt-set: ${project-dept}-${project-unique-id}-budget
  namespace: "config-control"
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
  labels:
    vanity-name: "deptenv-testProject" # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
    classification: class # kpt-set: ${project-classification}
spec:
  billingAccountRef:
    external: "016B6D-6AB281-505940" # kpt-set: ${billing-id}
  displayName: dept-testProject-budget # kpt-set: ${project-dept}-${project-vanity-name}-budget
  budgetFilter:
    projects:
      - name: "deptenv-01hq9k6djknb0v0emv93wqkw42" # kpt-set: ${project-dept}${project-env}-${project-unique-id}
    calendarPeriod: "YEAR"
  amount:
    specifiedAmount:
      currencyCode: "CAD"
      units: 2000
  thresholdRules:
    - thresholdPercent: 0.5
      spendBasis: "CURRENT_SPEND"
    - thresholdPercent: 0.9
      spendBasis: "CURRENT_SPEND"
    - thresholdPercent: 1.0
      spendBasis: "CURRENT_SPEND"
