apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: dept-01hq9jpysjmq8pt5g636vyxms3-folder # kpt-set: ${project-dept}-${project-unique-id}-folder
  namespace: "config-control"
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
  labels:
    vanity-name: "deptenv-test-project" # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
    classification: classification # kpt-set: ${project-classification}
spec:
  displayName: dept-test-project # kpt-set: ${project-dept}-${project-vanity-name}
  folderRef:
    external: "712587760826" # kpt-set: ${parent-folder-id}
