apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: dept-01hq9k6djknb0v0emv93wqkw42-folder # kpt-set: ${project-dept}-${project-unique-id}-folder
  namespace: "config-control"
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
  labels:
    vanity-name: "deptenv-testProject" # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
    classification: class # kpt-set: ${project-classification}
spec:
  displayName: dept-testProject # kpt-set: ${project-dept}-${project-vanity-name}
  folderRef:
    external: "712587760826" # kpt-set: ${parent-folder-id}
