apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  # This should be the same as project ID
  name: "deptenv-01hq9k6djknb0v0emv93wqkw42" # kpt-set: ${project-dept}${project-env}-${project-unique-id}
  namespace: "config-control"
  labels:
    vanity-name: "deptenv-testProject" # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
    classification: class # kpt-set: ${project-classification}
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: deptenv-testProject # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
  billingAccountRef:
    external: "016B6D-6AB281-505940" # kpt-set: ${billing-id}
  folderRef:
    name: dept-01hq9k6djknb0v0emv93wqkw42-folder # kpt-set: ${project-dept}-${project-unique-id}-folder
